import React, { useState, useEffect } from "react";
import { BookOpen, Copy, Download, RefreshCw, Check, Sparkles, AlertCircle } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import Markdown from "react-markdown";
import { jsPDF } from "jspdf";
import { generateStudyNotes } from "../services/api";

interface StudyNotesPanelProps {
  learningGoal: string;
}

export default function StudyNotesPanel({ learningGoal }: StudyNotesPanelProps) {
  const [loading, setLoading] = useState(false);
  const [notes, setNotes] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [iteration, setIteration] = useState(1);

  const fetchNotes = async (currentIteration = iteration, isRegenerate = false) => {
    setLoading(true);
    setError(null);
    try {
      const result = await generateStudyNotes(learningGoal, {
        iteration: currentIteration,
        regenerate: isRegenerate,
        seed: Date.now()
      });
      setNotes(result.notes);
    } catch (err: any) {
      console.error(err);
      setError(
        err.response?.data?.error || 
        "Failed to generate study notes. Please try again or check your Gemini API configuration."
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNotes(1, false);
  }, [learningGoal]);

  const handleRegenerate = () => {
    const nextIteration = iteration + 1;
    setIteration(nextIteration);
    fetchNotes(nextIteration, true);
  };

  const handleCopy = () => {
    if (!notes) return;
    navigator.clipboard.writeText(notes);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = () => {
    if (!notes) return;
    const doc = new jsPDF();
    
    doc.setProperties({
      title: `Study Masterclass: ${learningGoal}`,
      subject: "Lumina AI Study Notes",
      author: "Lumina AI"
    });

    // Primary Header Banner
    doc.setFillColor(124, 92, 255); // primary
    doc.rect(0, 0, 210, 38, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("LUMINA AI STUDY MASTERCLASS", 15, 16);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.text(`Topic: ${learningGoal} | Edition #${iteration}`, 15, 25);
    doc.text(`Generated by Lumina AI Copilot | Comprehensive 10-Module Study Handbook`, 15, 32);

    doc.setTextColor(30, 41, 59);
    let y = 48;
    const pageHeight = 297; 
    const margin = 15;
    const bottomMargin = 22;

    const cleanNotes = notes
      .replace(/<details>[\s\S]*?<summary>(.*?)<\/summary>/g, "\n[DEEP DIVE: $1]\n")
      .replace(/<\/details>/g, "\n")
      .replace(/<[^>]+>/g, "")
      .replace(/#+\s+(.*)/g, "\n$1\n")
      .replace(/\*\*(.*?)\*\*/g, "$1")
      .replace(/`(.*?)`/g, "$1");

    const lines = doc.splitTextToSize(cleanNotes, 180);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      if (y > pageHeight - bottomMargin) {
        doc.addPage();
        y = margin + 8;
      }

      const isHeader = line.startsWith("Module") || line.startsWith("MODULE") || line.startsWith("Chapter") || line.startsWith("CHAPTER") || line.startsWith("##") || line.startsWith("1.") || line.startsWith("2.") || line.startsWith("3.") || line.startsWith("4.") || line.startsWith("5.") || line.startsWith("6.") || line.startsWith("7.") || line.startsWith("8.") || line.startsWith("9.") || line.startsWith("10.");

      if (isHeader) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(124, 92, 255);
        doc.text(line, margin, y);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(30, 41, 59);
      } else {
        doc.text(line, margin, y);
      }
      y += 5.2; 
    }

    // Add page numbers
    const totalPages = doc.internal.pages.length - 1;
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Lumina AI Study Handbook — Page ${p} of ${totalPages}`, 105, 290, { align: "center" });
    }

    doc.save(`Lumina_Masterclass_${learningGoal.toLowerCase().replace(/[^a-z0-9]+/g, "_")}.pdf`);
  };

  return (
    <div id="study-notes-section" className="glass-card border border-[var(--border)] rounded-3xl p-6 shadow-[var(--shadow-lg)] space-y-6 mt-8 bg-[var(--surface)]">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[var(--border)] pb-4">
        <div className="flex items-center space-x-3">
          <div className="p-2.5 bg-primary/10 text-primary border border-primary/20 rounded-2xl">
            <BookOpen className="h-5 w-5" />
          </div>
          <div>
            <h3 className="text-lg font-sans font-bold text-[var(--text-primary)]">
              AI Comprehensive Study Masterclass
            </h3>
            <p className="text-xs text-[var(--text-muted)] font-medium">
              10 exhaustive modules with code samples, definitions, architecture breakdowns, and cheat sheets.
            </p>
          </div>
        </div>

        {notes && !loading && (
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-4 py-2 bg-[var(--surface-secondary)] border border-[var(--border)] hover:border-primary/40 rounded-xl text-xs font-bold text-[var(--text-primary)] transition-all flex items-center space-x-1 cursor-pointer shadow-sm"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-accent" />
                  <span className="text-accent">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5 text-primary" />
                  <span>Copy Notes</span>
                </>
              )}
            </button>
            <button
              onClick={handleDownloadPDF}
              className="px-4 py-2 btn-premium-primary rounded-xl text-xs font-bold transition-all flex items-center space-x-1 cursor-pointer border border-transparent shadow-md"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download PDF</span>
            </button>
            <button
              onClick={handleRegenerate}
              className="p-2 bg-[var(--surface-secondary)] hover:bg-primary/10 text-[var(--text-muted)] hover:text-[var(--text-primary)] rounded-xl transition-all border border-[var(--border)] cursor-pointer"
              title="Regenerate fresh masterclass notes"
            >
              <RefreshCw className="h-4 w-4" />
            </button>
          </div>
        )}
      </div>

      <AnimatePresence mode="wait">
        {loading ? (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center justify-center py-16 space-y-6"
          >
            {/* Premium Holographic Loading Orb Animation */}
            <div className="relative w-20 h-20 flex items-center justify-center">
              <div className="absolute inset-0 rounded-full border-2 border-primary/20 border-t-primary animate-spin" />
              <div className="absolute inset-2 rounded-full border border-secondary/10 border-b-secondary animate-spin" style={{ animationDirection: "reverse", animationDuration: "1.5s" }} />
              <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-primary to-secondary animate-pulse shadow-[0_0_20px_rgba(124,92,255,0.6)]" />
            </div>

            <div className="text-center space-y-1">
              <p className="text-sm font-bold text-[var(--text-primary)]">Lumina AI Compiling 10-Module Masterclass...</p>
              <p className="text-xs text-[var(--text-muted)]">Structuring theoretical architecture, practical code blocks, and cheat sheets.</p>
            </div>
          </motion.div>
        ) : error ? (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="bg-rose-500/10 border border-rose-500/20 p-4 rounded-2xl flex items-start space-x-3 text-sm text-rose-500"
          >
            <AlertCircle className="h-5 w-5 text-rose-500 shrink-0 mt-0.5" />
            <div className="flex-1 space-y-2">
              <p className="font-bold text-[var(--text-primary)]">Generation Notice</p>
              <p className="text-xs leading-normal opacity-90">{error}</p>
              <button
                onClick={handleRegenerate}
                className="mt-2 px-3 py-1.5 btn-premium-primary rounded-lg text-xs font-bold cursor-pointer"
              >
                <RefreshCw className="h-3 w-3" />
                <span>Retry Generation</span>
              </button>
            </div>
          </motion.div>
        ) : notes ? (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="bg-[var(--surface-secondary)] border border-[var(--border)] rounded-2xl p-6 sm:p-8"
          >
            {/* Notion style Markdown body container */}
            <div className="markdown-body text-[var(--text-primary)] leading-relaxed space-y-4">
              <Markdown>{notes}</Markdown>
            </div>
          </motion.div>
        ) : (
          <div className="flex flex-col items-center justify-center py-12 text-center text-[var(--text-muted)]">
            <Sparkles className="h-8 w-8 mb-2 text-primary" />
            <p className="text-sm font-medium">Ready to compile notes.</p>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
